### ISSUE TITLE
Toothpaste not found in Package control

### ISSUE THREAD

**Issue by dsincl12** [imcatnoone/toothpaste#1]
Searching for toothpaste in Package control doesn't resolve the theme.

**Comment by imcatnoone** [comment]
Hey @dsincl12 thanks a bunch for opening a ticket for this. I'm looking into it now. I was able to find it, which is odd, but you're not the only one having this issue. Were you able to install it manually?

**Comment by dsincl12** [comment]
Yeah no problems installing it manually. https://packagecontrol.io/search/toothpaste returns "No packages matched your search terms" as well.

**Comment by fspinillo** [comment]
I too am having trouble installing from Package Control. Additionally, when trying to install manually to either /Packages or /Packages/User results in an error:

> Error loading colour scheme Packages/toothpaste.tmTheme: Error parsing plist xml: expected = in file Packages/toothpaste.tmTheme on line: 50

**Comment by imcatnoone** [comment]
@dsincl12 Thanks! That occurred for me as well, actually. Which is truly odd considering I can _find_ it in package control o_O

@fspinillo Were you able to install it at all manually despite the error?

**Comment by fspinillo** [comment]
@imcatnoone unfortunately, no. It alerts me with the same error 3 times and then the theme is just solid white background with black text.

I am using ST3 and I noticed your guide is for ST2, but I've been able to get other ST2 specific themes to work in the past.

**Comment by imcatnoone** [comment]
@fspinillo ah! that is the reason more than likely, because manual for everyone else using 2 so far hasn't been a problem. It's probably because 3 is in beta, no? Either way, going to see what I need to do to port that over for 3. Thanks a bunch for pinging me about this, Frank! Either follow the repo or [me on twitter](http://twitter.com/imcatnoone) to keep up with updates.

**Comment by dsincl12** [comment]
I'm running Sublime Text 3 build 3083 without issues on 3 PC's and a Mac with Soda and Toothpaste.

**Comment by imcatnoone** [comment]
@dsincl12 @fspinillo Hey you two, this seems to have been an issue on my end. Not any of yours or Sublime (sort of). Should be available in package control soon! Will keep you posted as soon as it is. Thanks for your patience. :+1:

**Comment by tleruitte** [comment]
Toothpaste is still missing in Package Control: https://packagecontrol.io/search/toothpaste
I installed it manually successfully though.
