### ISSUE TITLE
Manual steps to install it in Windows

### ISSUE THREAD

**Issue by jm-kumaresh** [imcatnoone/toothpaste#10]
Its not listed on package control. I'm using Sublime Text 3. Let me know how to install it manually on windows machine.

Thanks

**Comment by timothyis** [comment]
This is a duplicate of #1. Please read issues before posting a new one. 

Also, the instructions for manual installation are in the [readme](https://github.com/imcatnoone/toothpaste#manually)... Steps shouldn't differ too much on windows.

**Comment by imcatnoone** [comment]
@jm-kumaresh Hey! Sorry you're experiencing some hiccups. I'm almost positive I can confirm what @CodeTheory just said. It should be the same manual instructions on a windows machine—give or take. I'll confirm this though and get back to you. It may be an issue with Sublime Text 3. I've already opened a ticket for that here #2. Going to look into that this weekend.
