### ISSUE TITLE
Terminal theme

### ISSUE THREAD

**Issue by lachlanjc** [imcatnoone/toothpaste#37]
Toothpaste is so good, we need a Terminal theme :smile:

**Comment by chrisfinazzo** [comment]
For something like this, two questions that come to mind...
1. How are colors defined? The built-in Terminal themes have hex values in their `.plist`, is that enough?
2. Is there anything else that should be defined? Things like cursor behavior have a few key-value pairs that might need to be changed 🤔

**Comment by ornithocoder** [comment]
Hi @lachlanjc @chrisfinazzo, I've a pull request for Terminal profile [here](https://github.com/imcatnoone/toothpaste/pull/54).

**Comment by ornithocoder** [comment]
Merged into master. Issue can be closed.
